### ISSUE TITLE
Add JWT Tokens expiration Date

### ISSUE THREAD

**Issue by shadowshot-x** [shadowshot-x/micro-product-go#1]
I have created my own JWT Tokens and the payload contains an exp field. However, I have not implemented the JWT expiry mechanism. Maybe you can help to add a time check for the JWT and return an error if the current time has passed the expiration timestamp.

**Comment by adzo261** [comment]
Hey, I would do like to do this one.

**Comment by shadowshot-x** [comment]
Hi @adzo261, Awesome! I will assign this issue to you. It would also be a great help if you could add some unit test cases for your functionality.  You can fork the project and get started! Happy Hacking! Do reach out if you need any help.

**Comment by shadowshot-x** [comment]
Hi @adzo261 , any progress on this issue?

**Comment by adzo261** [comment]
Hi, I was lately busy with some personal commitments. I would finish it by this week.
