### ISSUE TITLE
Take care of Flushing Buffered logs

### ISSUE THREAD

**Issue by shadowshot-x** [shadowshot-x/micro-product-go#18]
Need to call `Sync` method of Zap before exiting the code.

**Comment by Mayhul-Jindal** [comment]
Hey @shadowshot-x! I want to ask if this project still **active** and comes under **Hackertoberfest** ?

**Comment by shadowshot-x** [comment]
Hey @Mayhul-Jindal. Yes, this is open and active. Apologize for the late reply
