### ISSUE TITLE
Add Logging using Zap Logger

### ISSUE THREAD

**Issue by shadowshot-x** [shadowshot-x/micro-product-go#5]
Currently, I don't send anything to the Stdout and so when an error occurs, it is impossible to detect the origination of the error. Try to implement the Logging using [Uber Zap Logger](https://github.com/uber-go/zap) where the errors are encountered or wherever necessary.

**Comment by DonRenando** [comment]
Hi, i'm interested in working on it

**Comment by shadowshot-x** [comment]
Hi @DonRenando, Sure I will assign it to you. You can fork the project and get started!
